<a href="https://colab.research.google.com/github/King-Steve-Kuria/Machine-Learning/blob/main/Introduction_to_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import tensorflow as tf #call the function

Assume we define an input to the network (x) and the variable (parameters) w1, b1, w2, b2.
We feed this to the network

In [ ]:
x = np.random.normal(size = [1,4]).astype('float32')

In [ ]:
x

array([[-0.47073025,  0.37153766, -1.0662918 , -0.27978653]],
      dtype=float32)

In [ ]:
init = tf.keras.initializers.RandomNormal()

In [ ]:
init

In [ ]:
w1 = tf.Variable(init(shape = [4,3]))

In [ ]:
w1

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.0401734 , -0.03405194,  0.01179464],
       [-0.03820146,  0.00198782,  0.03907048],
       [ 0.04702323,  0.04600145,  0.12416788],
       [-0.05178835,  0.02359594,  0.00855441]], dtype=float32)>

In [ ]:
type(w1)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
b1 = tf.Variable(init(shape = [1,3]))

In [ ]:
b1

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[ 0.00590887,  0.06594347, -0.02377008]], dtype=float32)>

the matrices are 4 by 3 /// 1 by 3

In [ ]:
w2 = tf.Variable(init(shape = [3,2]))

In [ ]:
w2

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.02374139, -0.01243823],
       [ 0.020197  ,  0.01279376],
       [-0.06224916, -0.02023866]], dtype=float32)>

In [ ]:
b2 = tf.Variable(init(shape = [1,2]))

In [ ]:
b2

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[-0.02960641, -0.08611146]], dtype=float32)>

w1, w2, b1, b2 are all tensorflow variables, behave in a similar with typical python variables

In [ ]:
@tf.function
def forward(x,w,b, act):
  return act(tf.matmul(x,w)+b)

In [ ]:
h = forward(x,w1,b1,tf.nn.sigmoid)

In [ ]:
h

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.4842937 , 0.50676423, 0.46266997]], dtype=float32)>